name: CI

on:
  push:

permissions:
  contents: write
  packages: write

jobs:
  publish_docker:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4

      # Set up QEMU and Buildx for multi-platform builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Set the lowercase repository name using a shell command
      - name: Set DOCKER_REPO env
        run: |
          REPO_NAME_LOWERCASE=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "DOCKER_REPO=$REPO_NAME_LOWERCASE" >> $GITHUB_ENV

      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push images
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          # Now we can safely use the environment variable
          tags: |
            ghcr.io/${{ env.DOCKER_REPO }}:latest
